<?php
require_once 'db.php';

$password = "123";
$new_hash = password_hash($password, PASSWORD_BCRYPT);

$sql = "UPDATE users SET password = ? WHERE username = 'admin'";
$stmt = $conn->prepare($sql);
$stmt->bind_param("s", $new_hash);

if ($stmt->execute()) {
    echo "Successfully updated! <br>";
    echo "New Hash generated by your server: " . $new_hash . "<br>";
    echo "Now go to login.php and use password: 123";
} else {
    echo "Error: " . $conn->error;
}
?>